import { Holding } from "./types";

/**
 * Mock Financial Information Provider (FIP) response.
 *
 * In production this data arrives via the Account Aggregator (AA) framework:
 *   User consent -> AA (OneMoney/CAMS) -> FIP (bank/depository/AMC) -> Sarthi.
 * For the demo we simulate that fetch with a realistic portfolio and latency.
 */

export const MOCK_PORTFOLIO: Holding[] = [
  {
    id: "bank-hdfc-savings",
    type: "bank",
    provider: "HDFC Bank",
    providerCode: "hdfc",
    label: "Savings Account",
    maskedNumber: "•••• 4521",
    identifier: "50100XXXXX4521",
    value: 185400,
    nominee: { name: "Priya Sharma", relationship: "Spouse", verified: true },
    detail: "Salary account · Bengaluru",
    fixUrl: "https://www.hdfcbank.com/personal/ways-to-bank/nominee",
  },
  {
    id: "bank-sbi-savings",
    type: "bank",
    provider: "State Bank of India",
    providerCode: "sbi",
    label: "Savings Account",
    maskedNumber: "•••• 8890",
    identifier: "30012XXXXX8890",
    value: 42300,
    nominee: undefined,
    detail: "Home-town branch · Lucknow",
    fixUrl: "https://retail.onlinesbi.sbi/nominee.html",
  },
  {
    id: "bank-icici-fd",
    type: "fd",
    provider: "ICICI Bank",
    providerCode: "icici",
    label: "Fixed Deposit",
    maskedNumber: "FD •••• 7712",
    identifier: "FD-009812",
    value: 250000,
    nominee: { name: "Priya Sharma", relationship: "Spouse", verified: true },
    detail: "Matures Apr 2027",
    fixUrl: "https://www.icicibank.com/nominee",
  },
  {
    id: "demat-cdsl",
    type: "demat",
    provider: "CDSL",
    providerCode: "cdsl",
    label: "Demat Account (BO ID)",
    maskedNumber: "•••• 3318",
    identifier: "1208XXXXXXXX3318",
    value: 612750,
    nominee: undefined,
    detail: "Via Zerodha · 14 holdings",
    fixUrl: "https://www.cdslindia.com/cas/Nominee.html",
  },
  {
    id: "demat-nsdl",
    type: "demat",
    provider: "NSDL",
    providerCode: "nsdl",
    label: "Demat Account (DP ID)",
    maskedNumber: "•••• 5594",
    identifier: "IN300XXX",
    value: 98000,
    nominee: { name: "Arjun Sharma", relationship: "Son", verified: true },
    detail: "Via HDFC Securities",
    fixUrl: "https://nsdl.co.in/nominee.php",
  },
  {
    id: "mf-cams-1",
    type: "mutual_fund",
    provider: "CAMS",
    providerCode: "cams",
    label: "Equity Fund Folio",
    maskedNumber: "•••• 2244",
    identifier: "98765432/44",
    value: 305200,
    nominee: { name: "Priya Sharma", relationship: "Spouse", verified: true },
    detail: "SIP active · ₹5,000/mo",
    fixUrl: "https://www.mfcentral.com",
  },
  {
    id: "mf-kfintech-1",
    type: "mutual_fund",
    provider: "KFintech",
    providerCode: "kfintech",
    label: "ELSS Folio",
    maskedNumber: "•••• 9081",
    identifier: "55667788/90",
    value: 120000,
    nominee: undefined,
    detail: "Lock-in ended 2025",
    fixUrl: "https://www.mfcentral.com",
  },
  {
    id: "insurance-lic",
    type: "insurance",
    provider: "LIC of India",
    providerCode: "lic",
    label: "Life Insurance Policy",
    maskedNumber: "•••• 7715",
    identifier: "Policy 29XXXXXXXX",
    value: 1000000,
    nominee: { name: "Priya Sharma", relationship: "Spouse", verified: true },
    detail: "Sum assured ₹10L",
    fixUrl: "https://licindia.in/nominee",
  },
  {
    id: "ppf-sbi",
    type: "ppf",
    provider: "State Bank of India",
    providerCode: "sbi",
    label: "PPF Account",
    maskedNumber: "•••• 6102",
    identifier: "PPF-XXXX6102",
    value: 347800,
    nominee: undefined,
    detail: "Matures 2032",
    fixUrl: "https://retail.onlinesbi.sbi/nominee.html",
  },
];
